version: '2'
services:
  app:
    build: ./infra/app
    volumes:
      - ./project:/var/www
    links:
      - mysql
  web:
    build: ./infra/web
    ports:
      - "8081:80"
    volumes:
      - ./project:/var/www
    links:
      - app
      - redis
  redis:
    build: ./infra/redis
    ports:
      - 6379:6379
    restart: always
  mysql:
    build: ./infra/mysql
    ports:
      - "3306:3306"
    volumes:
      - ./infra/mysql/mysql-data:/var/lib/mysql
      - ./infra/mysql/sqls:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1